# Generated by Django 6.0 on 2025-12-26 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('broker', models.CharField(max_length=50)),
                ('demat_acc', models.CharField(blank=True, max_length=50)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('is_applied', models.BooleanField(default=False, verbose_name='Applied?')),
                ('allotment_status', models.CharField(choices=[('Pending', 'Pending'), ('Allotted', 'Allotted ✅'), ('Not Allotted', 'Not Allotted ❌')], default='Pending', max_length=20)),
                ('upi_request_sent', models.BooleanField(default=False, verbose_name='UPI Sent?')),
                ('payment_cleared', models.BooleanField(default=False, verbose_name='Payment Cleared?')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit_share_45', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('seller_name', models.CharField(blank=True, max_length=50, verbose_name='Who Sell?')),
                ('selling_method', models.CharField(blank=True, max_length=50, verbose_name='How Sell?')),
                ('payout_done', models.BooleanField(default=False, verbose_name='Paid to Partner?')),
                ('device_login', models.CharField(blank=True, max_length=50, verbose_name='Logged in Where?')),
                ('pending_task', models.TextField(blank=True)),
                ('screenshot_sent', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ipo')),
            ],
        ),
    ]
