# Generated by Django 6.0 on 2025-12-26 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapp',
            name='device_login',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientapp',
            name='payment_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientapp',
            name='payout_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientapp',
            name='seller_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientapp',
            name='selling_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientapp',
            name='upi_request_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MasterClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('broker', models.CharField(max_length=50)),
                ('demat_acc', models.CharField(blank=True, max_length=50)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
